### PR TITLE
Implement templateless PCR

### PR DESCRIPTION
**Pull request by dgruano**
Here are the frontend changes that would go with https://github.com/manulera/ShareYourCloning_backend/pull/111

### CODE REVIEW

**Comment by manulera** [comment]
Hi @dgruano that's great, thank you! 🚀🚀🚀🚀 

I am happy you managed to understand how things are organised in the repo, despite the lack of docs of the code. Let me know if you found something particularly hard to figure out so that I can improve the readme.

I think here we could prevent a lot of code duplication by re-using `SourcePCR` and adding a boolean prop `templateLess` to it:
* If `templateLess`, don't render the mismatches field
* Inside `onSubmit`, change the sendPostRequest for each case (I think the rest is actually fine, since `inputEntities` will be an empty list.
* Then, you could do something like:

```jsx
case 'templateless_pcr':
      specificSource = <SourcePCR {...{ sourceId, templateLess: true } } />; break;
```

Let me know if you want to implement those changes.

I can add the tests myself, unless you want to try. Cypress e2e tests take a second to get used to, so I am happy to do it myself. If you want to give it a go, I can also show you how to do it. Entirely up to you!

**Comment by manulera** [comment]
By the way, I added you as a collaborator of the repository so now you can create branches and make the pull request from it.

**Comment by dgruano** [comment]
Implemented the changes and added a quick fix for #120.

**Comment by manulera** [comment]
Perfect! And good point about templateLess not being needed. Indeed it can be removed and infer it from inputEntities being empty.

I will wait for the backend PR to go in and include the tests (the frontend tests run the server to test that all works as expected)

**Review by manulera — APPROVED** [review]

**Comment by manulera** [comment]
I merge into an internal branch to add the tests there, then I will merge into master.

**Pull request merged**
